// js/map.js
// 天下図・侵攻

let selectedProvince=null,currentEnemy=null;


function playerProvinceCount(){return PROVINCES.filter(p=>p.clan==='player').length;}

function drawStrategicMap(){const canvas=$('strategic-map');if(!canvas)return;const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#060e04';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(200,150,12,.04)';ctx.lineWidth=1;for(let x=0;x<W;x+=28){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=28){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}PROVINCES.forEach(p=>{p.adj.forEach(adjId=>{if(adjId<=p.id)return;const q=PROVINCES.find(x=>x.id===adjId);if(!q)return;ctx.strokeStyle='rgba(200,150,12,.15)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();});});PROVINCES.forEach(p=>{const isPlayer=p.clan==='player',isSel=selectedProvince&&selectedProvince.id===p.id;const color=CLAN_COLORS[p.clan]||'#444';const r=17;ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(p.x+2,p.y+2,r+2,r*.55+2,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.strokeStyle=isSel?'#ffee44':isPlayer?'#ffc800':'rgba(255,255,255,.18)';ctx.lineWidth=isSel?3:isPlayer?2:1;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();if(isSel){ctx.save();ctx.shadowColor='#ffee44';ctx.shadowBlur=16;ctx.strokeStyle='#ffee44';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,r+4,0,Math.PI*2);ctx.stroke();ctx.restore();}if(isPlayer){ctx.save();ctx.shadowColor='#ffc800';ctx.shadowBlur=8;ctx.strokeStyle='#ffc800';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y,r+3,0,Math.PI*2);ctx.stroke();ctx.restore();}ctx.fillStyle=isPlayer?'#ffee88':'#f0e8c8';ctx.font='bold 9px DotGothic16,monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.name,p.x,p.y);ctx.fillStyle='rgba(245,228,180,.5)';ctx.font='7px sans-serif';ctx.fillText(p.strength,p.x,p.y+r+8);});ctx.fillStyle='rgba(200,150,12,.7)';ctx.font='9px DotGothic16,monospace';ctx.textAlign='left';ctx.textBaseline='top';ctx.fillText('🟡 自領地　支配:'+playerProvinceCount()+'/'+PROVINCES.length+'国',6,H-16);}

function openMap(){selectedProvince=null;$('map-province-info').textContent='国をタップして侵攻先を選択';$('invade-btn').style.display='none';openModal('map-modal');setTimeout(()=>{const canvas=$('strategic-map');if(!canvas)return;const body=canvas.parentElement;if(body){canvas.width=body.clientWidth-20||320;canvas.height=Math.max(350,body.clientHeight-56);}drawStrategicMap();canvas.onclick=e=>{const rect=canvas.getBoundingClientRect();const sx=canvas.width/rect.width,sy=canvas.height/rect.height;const mx=(e.clientX-rect.left)*sx,my=(e.clientY-rect.top)*sy;const hit=PROVINCES.find(p=>Math.hypot(p.x-mx,p.y-my)<21);if(!hit)return;if(hit.clan==='player'){selectedProvince=null;$('invade-btn').style.display='none';$('map-province-info').innerHTML='<span style="color:var(--gold)">【自領地】'+hit.name+'　勢力: '+hit.strength+'</span>';}else{const pIds=PROVINCES.filter(p=>p.clan==='player').map(p=>p.id);const isAdj=hit.adj.some(id=>pIds.includes(id));selectedProvince=hit;if(isAdj){$('map-province-info').innerHTML='<span style="color:#ffdd44">侵攻先: '+hit.name+'　勢力 '+hit.strength+'</span>';$('invade-btn').style.display='block';}else{$('map-province-info').innerHTML='<span style="color:#ff8888">'+hit.name+'（隣接していないため侵攻不可）</span>';$('invade-btn').style.display='none';}}drawStrategicMap();};},120);}

function startInvasion(){if(!selectedProvince)return;currentEnemy={name:selectedProvince.name+'勢',strength:selectedProvince.strength,province:selectedProvince};closeModal('map-modal');openBattle();}
